In [1]:
import tensorflow as tf

# Basics Computation

In [45]:
v = tf.Variable(0)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>

In [47]:
a=tf.constant([2],name = 'constant_a')
b=tf.constant([3],name = 'constant_b')
a,b

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([3])>)

In [11]:
tf.print(a.numpy()[0])

2


In [16]:
@tf.function
def function(a,b):
    c=tf.add(a,b)
    print(c)
    return c

In [20]:
result = tf.add(a,b)
tf.print(result[0])

5


# Dimensions

In [23]:
scalar = tf.constant(2)
vector = tf.constant([5,6,2])
matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tensor = tf.constant([[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]])

In [24]:
scalar.shape

TensorShape([])

In [25]:
vector.shape

TensorShape([3])

In [26]:
matrix.shape

TensorShape([3, 3])

In [27]:
tensor.shape

TensorShape([1, 4, 3])

# Addition of Matrix

In [33]:
m1 = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
m2 = tf.constant([[7,8,9],[4,5,6],[1,2,3]])
@tf.function
def add(m1,m2):
    ans_m = tf.add(m1,m2)
    return ans_m

# Normally adding 
ans_ma = m1 +m2
print(ans_ma)

# Tensorflow adding 
ans_m = tf.add(m1,m2)
print(ans_m)

tf.Tensor(
[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]], shape=(3, 3), dtype=int32)


# Multiplication

In [42]:
m1 = tf.constant([[1,2],[4,5]])
m2 = tf.constant([[7,8],[4,5]])
@tf.function
def mul(m1,m2):
    return tf.matmul(m1,m2)

ans_m = mul(m1,m2)
# Tensorflow adding 
print(ans_m)

tf.Tensor(
[[15 18]
 [48 57]], shape=(2, 2), dtype=int32)


In [51]:
def i_one(v):
    v = tf.add(v,1)
    return v
for i in range(3):
    v=i_one(v)
    print(v)

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


# Operations

In [54]:
p = tf.constant([5])
q = tf.constant([7])
r = tf.add(p,q)
s = tf.subtract(p,q)

print ('r =: %s' % r)
    
print ('s =: %s' % s)

r =: tf.Tensor([12], shape=(1,), dtype=int32)
s =: tf.Tensor([-2], shape=(1,), dtype=int32)


In [71]:
import numpy as np
with tf.compat.v1.Session() as s:
    x = tf.constant(np.array([1.,2.,3.]))
    y = tf.constant(np.array([4.,5.,6.]))
    z = tf.tensordot(x,y,1)
    output = s.run(z)
    s.close()
print(output)

32.0
